In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
companies = pd.read_csv("/Users/mac/Downloads/Unicorn_Companies.csv")

Display 10 rows

In [5]:
companies.head(10)

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors
0,Bytedance,$180B,4/7/17,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$100B,12/1/12,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,$100B,7/3/18,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,$95B,1/23/14,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,$46B,12/12/11,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."
5,Canva,$40B,1/8/18,Internet software & services,Surry Hills,Australia,Oceania,2012,$572M,"Sequoia Capital China, Blackbird Ventures, Mat..."
6,Checkout.com,$40B,5/2/19,Fintech,London,United Kingdom,Europe,2012,$2B,"Tiger Global Management, Insight Partners, DST..."
7,Instacart,$39B,12/30/14,"Supply chain, logistics, & delivery",San Francisco,United States,North America,2012,$3B,"Khosla Ventures, Kleiner Perkins Caufield & By..."
8,JUUL Labs,$38B,12/20/17,Consumer & retail,San Francisco,United States,North America,2015,$14B,Tiger Global Management
9,Databricks,$38B,2/5/19,Data management & analytics,San Francisco,United States,North America,2013,$3B,"Andreessen Horowitz, New Enterprise Associates..."

Challenge questions: 
What does Date Joined Represent?
It represents the join

What does Select Investors mean?

In [7]:
# Convert to datetime

companies['Date Joined'] = pd.to_datetime(companies['Date Joined'])

In [8]:
#to confirm that the datetime has changed

companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   object
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1058 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1073 non-null   object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 84.0+ KB

In [10]:
companies.describe

<bound method NDFrame.describe of           Company Valuation Date Joined                         Industry  \
0       Bytedance     $180B  2017-04-07          Artificial intelligence
1          SpaceX     $100B  2012-12-01                            Other
2           SHEIN     $100B  2018-07-03  E-commerce & direct-to-consumer
3          Stripe      $95B  2014-01-23                          Fintech
4          Klarna      $46B  2011-12-12                          Fintech
...           ...       ...         ...                              ...
1069     Zhaogang       $1B  2017-06-29  E-commerce & direct-to-consumer
1070  Zhuan Zhuan       $1B  2017-04-18  E-commerce & direct-to-consumer
1071     Zihaiguo       $1B  2021-05-06                Consumer & retail
1072         Zopa       $1B  2021-10-19                          Fintech
1073        Zwift       $1B  2020-09-16  E-commerce & direct-to-consumer

               City  Country/Region      Continent  Year Founded Funding  \
0           Beijing           China           Asia          2012     $8B
1         Hawthorne   United States  North America          2002     $7B
2          Shenzhen           China           Asia          2008     $2B
3     San Francisco   United States  North America          2010     $2B
4         Stockholm          Sweden         Europe          2005     $4B
...             ...             ...            ...           ...     ...
1069       Shanghai           China           Asia          2012   $379M
1070        Beijing           China           Asia          2015   $990M
1071      Chongqing           China           Asia          2018    $80M
1072         London  United Kingdom         Europe          2005   $792M
1073     Long Beach   United States  North America          2014   $620M

                                       Select Investors
0     Sequoia Capital China, SIG Asia Investments, S...
1     Founders Fund, Draper Fisher Jurvetson, Rothen...
2     Tiger Global Management, Sequoia Capital China...
3           Khosla Ventures, LowercaseCapital, capitalG
4     Institutional Venture Partners, Sequoia Capita...
...                                                 ...
1069    K2 Ventures, Matrix Partners China, IDG Capital
1070                           58.com, Tencent Holdings
1071  Xingwang Investment Management, China Capital ...
1072  IAG Capital Partners, Augmentum Fintech, North...
1073    Novator Partners, True, Causeway Media Partners

[1074 rows x 10 columns]>

In [11]:
companies.shape

(1074, 10)

Create Year Joined Column

In [16]:
companies['Year Joined'] = companies['Date Joined'].dt.year
companies.head(10)

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined
0,Bytedance,$180B,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017
1,SpaceX,$100B,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012
2,SHEIN,$100B,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018
3,Stripe,$95B,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014
4,Klarna,$46B,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011
5,Canva,$40B,2018-01-08,Internet software & services,Surry Hills,Australia,Oceania,2012,$572M,"Sequoia Capital China, Blackbird Ventures, Mat...",2018
6,Checkout.com,$40B,2019-05-02,Fintech,London,United Kingdom,Europe,2012,$2B,"Tiger Global Management, Insight Partners, DST...",2019
7,Instacart,$39B,2014-12-30,"Supply chain, logistics, & delivery",San Francisco,United States,North America,2012,$3B,"Khosla Ventures, Kleiner Perkins Caufield & By...",2014
8,JUUL Labs,$38B,2017-12-20,Consumer & retail,San Francisco,United States,North America,2015,$14B,Tiger Global Management,2017
9,Databricks,$38B,2019-02-05,Data management & analytics,San Francisco,United States,North America,2013,$3B,"Andreessen Horowitz, New Enterprise Associates...",2019

In [17]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   object
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1058 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1073 non-null   object
 10  Year Joined       1074 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 92.4+ KB